const items = [
    {
        name: "CyberPowerPC- Gaming Computer",
        price: 1200,
        photo: "https://www.cyberpowerpc.com/images/cs/P428X/cs-450-169_400.png",
        description: "Gamer Master Gaming Desktop - AMD Ryzen 7 5700 - 16GB Memory - NVIDIA GeForce RTX 4060 Ti 8GB - 2TB SSD",
        quantity: 22,
        isFeatured: true,
    },
    {
        name: "CLX- Gaming Computer",
        price: 2500,
        photo: "https://m.media-amazon.com/images/I/81kEErgt6VL._AC_UF894,1000_QL80_.jpg",
        description: "CLX - SET Gaming Desktop - Intel Core i9-13900KF - 64GB Memory - NVIDIA GeForce RTX 4070 - 2TB NVMe M.2 SSD + 6TB HDD - Black",
        quantity: 34,
        isFeatured: false,
    },
    {
        name: "Dell Curved Gaming Monitor",
        price: 350,
        photo: "https://i5.walmartimages.com/asr/8ea32b5a-3177-4dc7-b4a2-6bd9cbc5f24a.964474d978927d83668a8ddb08c9d879.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF",
        description: "Dell - S3222DGM 32 LED Curved QHD FreeSync Gaming Monitor (DisplayPort, HDMI) - Black",
        quantity: 41,
        isFeatured: true,
    },
    {
        name: "Asus Flatscreen Gaming Monitor",
        price: 230,
        photo: "https://www.asus.com/media/global/gallery/85ssljuw0k4w2hbp_setting_xxx_0_90_end_2000.png",
        description: "ASUS - TUF Gaming 27 IPS FHD 1080P 165Hz 1ms FreeSync Premium Gaming Monitor (2 x HDMI, DisplayPort)",
        quantity: 12,
        isFeatured: false,
    },
    {
        name: "Razer Gaming Keyboard",
        price: 160,
        photo: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6531/6531755_sd.jpg;maxHeight=640;maxWidth=550",
        description: "Razer - BlackWidow V4 Full Size Wired Mechanical Green Switch Gaming Keyboard with Chroma RGB",
        quantity: 37,
        isFeatured: true,
    },
    {
        name: "Corsair Gaming Keyboard",
        price: 250,
        photo: "https://m.media-amazon.com/images/I/41uGCMCtc5L._AC_.jpg",
        description: "CORSAIR - K100 RGB Full-size Wired Mechanical OPX Linear Switch Gaming Keyboard with Elgato Stream Deck Software Integration",
        quantity: 54,
        isFeatured: false,
    },
    {
        name: "Razer Gaming Headset",
        price: 200,
        photo: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6538/6538209_sd.jpg",
        description: "Razer - BlackShark V2 Pro (2023) Wireless Esports Gaming Headset",
        quantity: 15,
        isFeatured: true,
    },
    {
        name: "Logitech Gaming Headet",
        price: 150,
        photo: "https://m.media-amazon.com/images/I/71xNjrzG69L._AC_UF894,1000_QL80_.jpg",
        description: "Logitech - G733 LIGHTSPEED Wireless Gaming Headset",
        quantity: 23,
        isFeatured: false,
    },
    {
        name: "HyperX Gaming Microphone",
        price: 50,
        photo: "https://in-media.apjonlinecdn.com/catalog/product/cache/b3b166914d87ce343d4dc5ec5117b502/5/1/519T2AA-1_T1680435499.png",
        description: "HyperX - SoloCast Wired Cardioid USB Condenser Gaming Microphone",
        quantity: 37,
        isFeatured: true,
    },
    {
        name: "Blue Gaming Microphone",
        price: 180,
        photo: "https://media.sweetwater.com/m/products/image/ad18021c79KsuYoHG4A027kTZC5hQMHQPkZmOtmF.jpg?quality=82&ha=ad18021c79914d4c",
        description: "Blue Microphones - Yeticaster Studio Professional Wired Multi-Pattern Condenser Microphone Desktop Bundle",
        quantity: 76,
        isFeatured: false,
    },
    {
        name: "Logitech Gaming Mouse",
        price: 50,
        photo: "https://m.media-amazon.com/images/I/516LT-kaCoL._AC_UF894,1000_QL80_.jpg",
        description: "Logitech - G502 HERO Wired Optical Gaming Mouse with RGB Lighting",
        quantity: 43,
        isFeatured: true,
    },
    {
        name: "Razer Gaming Mouse",
        price: 100,
        photo: "https://m.media-amazon.com/images/I/61M7B24YNEL._AC_UL400_.jpg",
        description: "Razer - Basilisk Ultimate Wireless Optical with HyperSpeed Technology and Charging Dock Gaming Mouse",
        quantity: 25,
        isFeatured: false,
    },
]